[{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/246628229","html_url":"https://github.com/elastic/elasticsearch/issues/20444#issuecomment-246628229","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/20444","id":246628229,"node_id":"MDEyOklzc3VlQ29tbWVudDI0NjYyODIyOQ==","user":{"login":"bleskes","id":1006375,"node_id":"MDQ6VXNlcjEwMDYzNzU=","avatar_url":"https://avatars1.githubusercontent.com/u/1006375?v=4","gravatar_id":"","url":"https://api.github.com/users/bleskes","html_url":"https://github.com/bleskes","followers_url":"https://api.github.com/users/bleskes/followers","following_url":"https://api.github.com/users/bleskes/following{/other_user}","gists_url":"https://api.github.com/users/bleskes/gists{/gist_id}","starred_url":"https://api.github.com/users/bleskes/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/bleskes/subscriptions","organizations_url":"https://api.github.com/users/bleskes/orgs","repos_url":"https://api.github.com/users/bleskes/repos","events_url":"https://api.github.com/users/bleskes/events{/privacy}","received_events_url":"https://api.github.com/users/bleskes/received_events","type":"User","site_admin":false},"created_at":"2016-09-13T09:36:14Z","updated_at":"2016-09-13T09:36:14Z","author_association":"MEMBER","body":"We try to reserve github for issues. For discussion/questions/help requests, I would ask you to use http://discuss.elastic.co\n\nA quick glance at your code shows at least one thing that's wrong: you need to deal with failures and respond to channel in your `public void onFailure(Throwable e) {}`. I guess that's why you don't hear back from the node.\n\nI'm closing this. If the above doesn't work, please ask in the forums.\n","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/246642002","html_url":"https://github.com/elastic/elasticsearch/issues/20444#issuecomment-246642002","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/20444","id":246642002,"node_id":"MDEyOklzc3VlQ29tbWVudDI0NjY0MjAwMg==","user":{"login":"xxwikluo","id":22166574,"node_id":"MDQ6VXNlcjIyMTY2NTc0","avatar_url":"https://avatars2.githubusercontent.com/u/22166574?v=4","gravatar_id":"","url":"https://api.github.com/users/xxwikluo","html_url":"https://github.com/xxwikluo","followers_url":"https://api.github.com/users/xxwikluo/followers","following_url":"https://api.github.com/users/xxwikluo/following{/other_user}","gists_url":"https://api.github.com/users/xxwikluo/gists{/gist_id}","starred_url":"https://api.github.com/users/xxwikluo/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/xxwikluo/subscriptions","organizations_url":"https://api.github.com/users/xxwikluo/orgs","repos_url":"https://api.github.com/users/xxwikluo/repos","events_url":"https://api.github.com/users/xxwikluo/events{/privacy}","received_events_url":"https://api.github.com/users/xxwikluo/received_events","type":"User","site_admin":false},"created_at":"2016-09-13T10:36:11Z","updated_at":"2016-09-13T10:46:30Z","author_association":"NONE","body":"Well, the lacking onFailure is only this test endpoint, the actual endpoints at least drops some stack traces like:\n\n```\n    @Override\n    public void onFailure(final Throwable e) {\n        try {\n            channel.sendResponse(new BytesRestResponse(channel, e));\n        } catch (IOException e1) {\n            logger.error(\"Failed to send failure response\", e1);\n        }\n    }\n```\n\nBut thanks for the reply will go search/ask in the forums.\n\nEdit: If I remember correctly there are no traces from the onFailure when this is observed ..\n","performed_via_github_app":null}]