[{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/264910427","html_url":"https://github.com/elastic/elasticsearch/issues/21979#issuecomment-264910427","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/21979","id":264910427,"node_id":"MDEyOklzc3VlQ29tbWVudDI2NDkxMDQyNw==","user":{"login":"HonzaKral","id":32132,"node_id":"MDQ6VXNlcjMyMTMy","avatar_url":"https://avatars0.githubusercontent.com/u/32132?v=4","gravatar_id":"","url":"https://api.github.com/users/HonzaKral","html_url":"https://github.com/HonzaKral","followers_url":"https://api.github.com/users/HonzaKral/followers","following_url":"https://api.github.com/users/HonzaKral/following{/other_user}","gists_url":"https://api.github.com/users/HonzaKral/gists{/gist_id}","starred_url":"https://api.github.com/users/HonzaKral/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/HonzaKral/subscriptions","organizations_url":"https://api.github.com/users/HonzaKral/orgs","repos_url":"https://api.github.com/users/HonzaKral/repos","events_url":"https://api.github.com/users/HonzaKral/events{/privacy}","received_events_url":"https://api.github.com/users/HonzaKral/received_events","type":"User","site_admin":false},"created_at":"2016-12-05T16:58:48Z","updated_at":"2016-12-05T16:58:48Z","author_association":"MEMBER","body":"Actually there is no need for `warnings` to be a part of the `do` actions. Instead it should be, like other assertions (like `match`) a separate independent action. So the example would be:\r\n```\r\n- do:\r\n        get:\r\n            index:    test\r\n            type:    test\r\n            id:        1\r\n- warning: '[index] is deprecated'\r\n- warning: ...\r\n```","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/264911492","html_url":"https://github.com/elastic/elasticsearch/issues/21979#issuecomment-264911492","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/21979","id":264911492,"node_id":"MDEyOklzc3VlQ29tbWVudDI2NDkxMTQ5Mg==","user":{"login":"nik9000","id":215970,"node_id":"MDQ6VXNlcjIxNTk3MA==","avatar_url":"https://avatars2.githubusercontent.com/u/215970?v=4","gravatar_id":"","url":"https://api.github.com/users/nik9000","html_url":"https://github.com/nik9000","followers_url":"https://api.github.com/users/nik9000/followers","following_url":"https://api.github.com/users/nik9000/following{/other_user}","gists_url":"https://api.github.com/users/nik9000/gists{/gist_id}","starred_url":"https://api.github.com/users/nik9000/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/nik9000/subscriptions","organizations_url":"https://api.github.com/users/nik9000/orgs","repos_url":"https://api.github.com/users/nik9000/repos","events_url":"https://api.github.com/users/nik9000/events{/privacy}","received_events_url":"https://api.github.com/users/nik9000/received_events","type":"User","site_admin":false},"created_at":"2016-12-05T17:02:19Z","updated_at":"2016-12-05T17:02:19Z","author_association":"CONTRIBUTOR","body":"I've always thought of `warnings` as the same kind of thing as `catch` so I put it in the same spot.\r\n\r\n> Actually there is no need for warnings to be a part of the do actions.\r\n\r\nThe argument for merging it into `do` is the same as the argument for merging `catch` into `do`. If you don't specify a `catch` clause then any failures fail the test. The same is true for `warnings`.\r\n\r\nI'm fine with moving it around but I think we should treat it the same as `catch`.","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/264912429","html_url":"https://github.com/elastic/elasticsearch/issues/21979#issuecomment-264912429","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/21979","id":264912429,"node_id":"MDEyOklzc3VlQ29tbWVudDI2NDkxMjQyOQ==","user":{"login":"HonzaKral","id":32132,"node_id":"MDQ6VXNlcjMyMTMy","avatar_url":"https://avatars0.githubusercontent.com/u/32132?v=4","gravatar_id":"","url":"https://api.github.com/users/HonzaKral","html_url":"https://github.com/HonzaKral","followers_url":"https://api.github.com/users/HonzaKral/followers","following_url":"https://api.github.com/users/HonzaKral/following{/other_user}","gists_url":"https://api.github.com/users/HonzaKral/gists{/gist_id}","starred_url":"https://api.github.com/users/HonzaKral/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/HonzaKral/subscriptions","organizations_url":"https://api.github.com/users/HonzaKral/orgs","repos_url":"https://api.github.com/users/HonzaKral/repos","events_url":"https://api.github.com/users/HonzaKral/events{/privacy}","received_events_url":"https://api.github.com/users/HonzaKral/received_events","type":"User","site_admin":false},"created_at":"2016-12-05T17:05:48Z","updated_at":"2016-12-05T17:05:48Z","author_association":"MEMBER","body":"`catch` imho needs to be a part of `do` because it tests an exception has been raised (which interrupts the flow of the code and therefore cannot be tested after the fact) whereas `warnings` just runs an assertion on the data returned, in this way it is just like `match` and other assertions.","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/264914971","html_url":"https://github.com/elastic/elasticsearch/issues/21979#issuecomment-264914971","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/21979","id":264914971,"node_id":"MDEyOklzc3VlQ29tbWVudDI2NDkxNDk3MQ==","user":{"login":"karmi","id":4790,"node_id":"MDQ6VXNlcjQ3OTA=","avatar_url":"https://avatars1.githubusercontent.com/u/4790?v=4","gravatar_id":"","url":"https://api.github.com/users/karmi","html_url":"https://github.com/karmi","followers_url":"https://api.github.com/users/karmi/followers","following_url":"https://api.github.com/users/karmi/following{/other_user}","gists_url":"https://api.github.com/users/karmi/gists{/gist_id}","starred_url":"https://api.github.com/users/karmi/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/karmi/subscriptions","organizations_url":"https://api.github.com/users/karmi/orgs","repos_url":"https://api.github.com/users/karmi/repos","events_url":"https://api.github.com/users/karmi/events{/privacy}","received_events_url":"https://api.github.com/users/karmi/received_events","type":"User","site_admin":false},"created_at":"2016-12-05T17:15:04Z","updated_at":"2016-12-05T17:15:04Z","author_association":"CONTRIBUTOR","body":"> `catch` (...) needs to be a part of `do` because it tests an exception has been raised (...), whereas `warnings` just runs an assertion on the data returned\r\n\r\nThat is what I wanted to say, but forgot, thanks @HonzaKral to making it clear!\r\n\r\nIn other words `catch` and `warnings` are not only semantically, but technically different, and `warnings` should be considered a clause similar to `match` (it operates on the response).","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/264915674","html_url":"https://github.com/elastic/elasticsearch/issues/21979#issuecomment-264915674","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/21979","id":264915674,"node_id":"MDEyOklzc3VlQ29tbWVudDI2NDkxNTY3NA==","user":{"login":"javanna","id":832460,"node_id":"MDQ6VXNlcjgzMjQ2MA==","avatar_url":"https://avatars1.githubusercontent.com/u/832460?v=4","gravatar_id":"","url":"https://api.github.com/users/javanna","html_url":"https://github.com/javanna","followers_url":"https://api.github.com/users/javanna/followers","following_url":"https://api.github.com/users/javanna/following{/other_user}","gists_url":"https://api.github.com/users/javanna/gists{/gist_id}","starred_url":"https://api.github.com/users/javanna/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/javanna/subscriptions","organizations_url":"https://api.github.com/users/javanna/orgs","repos_url":"https://api.github.com/users/javanna/repos","events_url":"https://api.github.com/users/javanna/events{/privacy}","received_events_url":"https://api.github.com/users/javanna/received_events","type":"User","site_admin":false},"created_at":"2016-12-05T17:17:38Z","updated_at":"2016-12-05T17:18:04Z","author_association":"MEMBER","body":"I think they are actually semantically the same because a test runner, at least that is what the java one does, should throw error if there's any warning returned. No do section should return any warning, like it should not return any non ok status code. If we do expect warnings to be returned, then we declare them and \"catch\" them. We may have failed to document this properly, but I don't see how this could work outside of `do`, that would be too late to catch the error thrown when warnings have been found in the response.","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/264916449","html_url":"https://github.com/elastic/elasticsearch/issues/21979#issuecomment-264916449","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/21979","id":264916449,"node_id":"MDEyOklzc3VlQ29tbWVudDI2NDkxNjQ0OQ==","user":{"login":"nik9000","id":215970,"node_id":"MDQ6VXNlcjIxNTk3MA==","avatar_url":"https://avatars2.githubusercontent.com/u/215970?v=4","gravatar_id":"","url":"https://api.github.com/users/nik9000","html_url":"https://github.com/nik9000","followers_url":"https://api.github.com/users/nik9000/followers","following_url":"https://api.github.com/users/nik9000/following{/other_user}","gists_url":"https://api.github.com/users/nik9000/gists{/gist_id}","starred_url":"https://api.github.com/users/nik9000/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/nik9000/subscriptions","organizations_url":"https://api.github.com/users/nik9000/orgs","repos_url":"https://api.github.com/users/nik9000/repos","events_url":"https://api.github.com/users/nik9000/events{/privacy}","received_events_url":"https://api.github.com/users/nik9000/received_events","type":"User","site_admin":false},"created_at":"2016-12-05T17:20:42Z","updated_at":"2016-12-05T17:20:42Z","author_association":"CONTRIBUTOR","body":"> whereas warnings just runs an assertion on the data returned\r\n\r\nThe lack of a `warnings` section asserts that no warnings were returned. In that way it is quite similar to `catch`. I'm fine with moving it if it is important to you but I think any argument for moving it should also be applied to `catch`.\r\n\r\n> We may have failed to document this properly, but I don't see how this could work outside of do, that would be too late to catch the error thrown when warnings have been found in the response.\r\n\r\nI mean, we could do it if we thought it was really important.\r\n\r\n","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/264919118","html_url":"https://github.com/elastic/elasticsearch/issues/21979#issuecomment-264919118","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/21979","id":264919118,"node_id":"MDEyOklzc3VlQ29tbWVudDI2NDkxOTExOA==","user":{"login":"karmi","id":4790,"node_id":"MDQ6VXNlcjQ3OTA=","avatar_url":"https://avatars1.githubusercontent.com/u/4790?v=4","gravatar_id":"","url":"https://api.github.com/users/karmi","html_url":"https://github.com/karmi","followers_url":"https://api.github.com/users/karmi/followers","following_url":"https://api.github.com/users/karmi/following{/other_user}","gists_url":"https://api.github.com/users/karmi/gists{/gist_id}","starred_url":"https://api.github.com/users/karmi/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/karmi/subscriptions","organizations_url":"https://api.github.com/users/karmi/orgs","repos_url":"https://api.github.com/users/karmi/repos","events_url":"https://api.github.com/users/karmi/events{/privacy}","received_events_url":"https://api.github.com/users/karmi/received_events","type":"User","site_admin":false},"created_at":"2016-12-05T17:30:17Z","updated_at":"2016-12-05T17:30:17Z","author_association":"CONTRIBUTOR","body":"> I think they are actually semantically the same because a test runner, at least that is what the java one does, should throw error if there's any warning returned.\r\n\r\nIf that's the case, then `warnings` is the same as `catch`, agreed. I had the assumption that the client would only _log_ the warnings, not throw an error. ","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/264920103","html_url":"https://github.com/elastic/elasticsearch/issues/21979#issuecomment-264920103","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/21979","id":264920103,"node_id":"MDEyOklzc3VlQ29tbWVudDI2NDkyMDEwMw==","user":{"login":"HonzaKral","id":32132,"node_id":"MDQ6VXNlcjMyMTMy","avatar_url":"https://avatars0.githubusercontent.com/u/32132?v=4","gravatar_id":"","url":"https://api.github.com/users/HonzaKral","html_url":"https://github.com/HonzaKral","followers_url":"https://api.github.com/users/HonzaKral/followers","following_url":"https://api.github.com/users/HonzaKral/following{/other_user}","gists_url":"https://api.github.com/users/HonzaKral/gists{/gist_id}","starred_url":"https://api.github.com/users/HonzaKral/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/HonzaKral/subscriptions","organizations_url":"https://api.github.com/users/HonzaKral/orgs","repos_url":"https://api.github.com/users/HonzaKral/repos","events_url":"https://api.github.com/users/HonzaKral/events{/privacy}","received_events_url":"https://api.github.com/users/HonzaKral/received_events","type":"User","site_admin":false},"created_at":"2016-12-05T17:33:53Z","updated_at":"2016-12-05T17:33:53Z","author_association":"MEMBER","body":"> The lack of a warnings section asserts that no warnings were returned. In that way it is quite similar to catch.\r\n\r\nThis is a good point, makes sense. I stand corrected.\r\n\r\n>  I had the assumption that the client would only log the warnings, not throw an error.\r\n\r\nI think the test should fail if it encounters an unexpected (== not declared) warning regardless of what the client would do. The same way a test fails when it has `catch`/`warning` defined yet doesn't actually detect any exception/warning.\r\n\r\nThanks @nik9000 and @javanna for the explanation, I am fine with `warnings` as they are.","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/264924256","html_url":"https://github.com/elastic/elasticsearch/issues/21979#issuecomment-264924256","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/21979","id":264924256,"node_id":"MDEyOklzc3VlQ29tbWVudDI2NDkyNDI1Ng==","user":{"login":"javanna","id":832460,"node_id":"MDQ6VXNlcjgzMjQ2MA==","avatar_url":"https://avatars1.githubusercontent.com/u/832460?v=4","gravatar_id":"","url":"https://api.github.com/users/javanna","html_url":"https://github.com/javanna","followers_url":"https://api.github.com/users/javanna/followers","following_url":"https://api.github.com/users/javanna/following{/other_user}","gists_url":"https://api.github.com/users/javanna/gists{/gist_id}","starred_url":"https://api.github.com/users/javanna/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/javanna/subscriptions","organizations_url":"https://api.github.com/users/javanna/orgs","repos_url":"https://api.github.com/users/javanna/repos","events_url":"https://api.github.com/users/javanna/events{/privacy}","received_events_url":"https://api.github.com/users/javanna/received_events","type":"User","site_admin":false},"created_at":"2016-12-05T17:49:13Z","updated_at":"2016-12-05T17:49:13Z","author_association":"MEMBER","body":"> I think the test should fail if it encounters an unexpected (== not declared) warning regardless of what the client would do. The same way a test fails when it has catch/warning defined yet doesn't actually detect any exception/warning.\r\n\r\nYep, that's how we implemented it on the java end. Closing then ;)\r\n\r\n","performed_via_github_app":null}]