[{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/356297515","html_url":"https://github.com/elastic/elasticsearch/issues/24860#issuecomment-356297515","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/24860","id":356297515,"node_id":"MDEyOklzc3VlQ29tbWVudDM1NjI5NzUxNQ==","user":{"login":"tlrx","id":642733,"node_id":"MDQ6VXNlcjY0MjczMw==","avatar_url":"https://avatars1.githubusercontent.com/u/642733?v=4","gravatar_id":"","url":"https://api.github.com/users/tlrx","html_url":"https://github.com/tlrx","followers_url":"https://api.github.com/users/tlrx/followers","following_url":"https://api.github.com/users/tlrx/following{/other_user}","gists_url":"https://api.github.com/users/tlrx/gists{/gist_id}","starred_url":"https://api.github.com/users/tlrx/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/tlrx/subscriptions","organizations_url":"https://api.github.com/users/tlrx/orgs","repos_url":"https://api.github.com/users/tlrx/repos","events_url":"https://api.github.com/users/tlrx/events{/privacy}","received_events_url":"https://api.github.com/users/tlrx/received_events","type":"User","site_admin":false},"created_at":"2018-01-09T14:23:21Z","updated_at":"2018-01-09T14:23:21Z","author_association":"MEMBER","body":"This issue fails every month or so in the last two years but didn't fail since Sept 17th 2017. Restore has been improved in #27493 so I'm curious to see if this failure will appear again on 5.6.6/6.0.2.\r\n\r\nPlease reopen if needed.","performed_via_github_app":null}]