[{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/311761787","html_url":"https://github.com/elastic/elasticsearch/issues/25454#issuecomment-311761787","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/25454","id":311761787,"node_id":"MDEyOklzc3VlQ29tbWVudDMxMTc2MTc4Nw==","user":{"login":"tbrooks8","id":862472,"node_id":"MDQ6VXNlcjg2MjQ3Mg==","avatar_url":"https://avatars3.githubusercontent.com/u/862472?v=4","gravatar_id":"","url":"https://api.github.com/users/tbrooks8","html_url":"https://github.com/tbrooks8","followers_url":"https://api.github.com/users/tbrooks8/followers","following_url":"https://api.github.com/users/tbrooks8/following{/other_user}","gists_url":"https://api.github.com/users/tbrooks8/gists{/gist_id}","starred_url":"https://api.github.com/users/tbrooks8/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/tbrooks8/subscriptions","organizations_url":"https://api.github.com/users/tbrooks8/orgs","repos_url":"https://api.github.com/users/tbrooks8/repos","events_url":"https://api.github.com/users/tbrooks8/events{/privacy}","received_events_url":"https://api.github.com/users/tbrooks8/received_events","type":"User","site_admin":false},"created_at":"2017-06-28T19:24:07Z","updated_at":"2017-06-28T19:24:07Z","author_association":"CONTRIBUTOR","body":"It appears that this asserting on this IOException message may not be dependable. It is not important that we do this, as we also assert on our application exception message. I have removed this problematic assertion.\r\n\r\nhttps://github.com/elastic/elasticsearch/commit/cad57959e11ae37936fa7dcf7cc4aaa4ba9b5bb0","performed_via_github_app":null}]