{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/25633","repository_url":"https://api.github.com/repos/elastic/elasticsearch","labels_url":"https://api.github.com/repos/elastic/elasticsearch/issues/25633/labels{/name}","comments_url":"https://api.github.com/repos/elastic/elasticsearch/issues/25633/comments","events_url":"https://api.github.com/repos/elastic/elasticsearch/issues/25633/events","html_url":"https://github.com/elastic/elasticsearch/issues/25633","id":241754363,"node_id":"MDU6SXNzdWUyNDE3NTQzNjM=","number":25633,"title":"Users unable Authenticate with LDAP account - Frequent LDAP timeout after few days","user":{"login":"jayannah","id":4325281,"node_id":"MDQ6VXNlcjQzMjUyODE=","avatar_url":"https://avatars0.githubusercontent.com/u/4325281?v=4","gravatar_id":"","url":"https://api.github.com/users/jayannah","html_url":"https://github.com/jayannah","followers_url":"https://api.github.com/users/jayannah/followers","following_url":"https://api.github.com/users/jayannah/following{/other_user}","gists_url":"https://api.github.com/users/jayannah/gists{/gist_id}","starred_url":"https://api.github.com/users/jayannah/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jayannah/subscriptions","organizations_url":"https://api.github.com/users/jayannah/orgs","repos_url":"https://api.github.com/users/jayannah/repos","events_url":"https://api.github.com/users/jayannah/events{/privacy}","received_events_url":"https://api.github.com/users/jayannah/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2017-07-10T15:32:03Z","updated_at":"2017-07-11T07:26:00Z","closed_at":"2017-07-11T07:26:00Z","author_association":"NONE","active_lock_reason":null,"body":"<!-- Bug report -->\r\nWe have ES cluster with dedicated Co-ordinator node in AWS region with high performance Ec2 instances r4.16xlarge . \r\n\r\nWe have installed x-pack and configured the LDAP details for users to login to ES or Kibana with their LDAP user credentails.   Around 10-15 users login every min approx. \r\n\r\nEverything will be working fine and all users will be able to login to ES and Kibana.. After few days, ES nodes unable to establish connection to LDAP and all users login fails (see logs at bottom).\r\n\r\nWhen I restart all the co-ordinator nodes (we have 3 co-ordinator nodes in the cluster & 9 data nodes, 4 master nodes dedicated) only, then everything will start working fine and all users are able to login//\r\n\r\nagain after few days, all user login fails... restarting co-ordinator nodes again solves for few days..\r\n\r\nPlease note: We are using the same 20s LDAP timeout connection in Splunk aswell and more than 1000+ users logs concurrently and we never seen any problem in Splunk connecting to LDAP. \r\n\r\nIn Elastic Node, we have increased 30s and still see the timeout problem.\r\n\r\nWhy the restart fixes the issue for few days? \r\n\r\n**Elasticsearch version**:\r\n5.4.2\r\n\r\n**Plugins installed**: []\r\n5.4.2\r\n\r\n**JVM version** (`java -version`):\r\n\"1.8.0_73\"\r\n\r\n**OS version** (`uname -a` if on a Unix-like system):\r\nLinux ip-200-xx-xx.xx.xxx.xx3.13.0-117-generic #164-Ubuntu SMP Fri Apr 7 11:05:26 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux\r\n\r\n**Description of the problem including expected versus actual behavior**:\r\nThe ES node unable to establish connection with LDAP hence users are unable to login with LDAP.\r\n\r\nAfter restarting Co-ordinator nodes, everything will be fine for few days.. and after few days again we see this issue.\r\n\r\nHere is the configuration file we have used. \r\n## cat /etc/elasticsearch/elasticsearch.yml\r\ncluster.name: horiz_prod1_escluster1_e\r\nnode.name: 10.200.x.x\r\nnode.master: false\r\nnode.data: false\r\nnode.ingest: false\r\nbootstrap.memory_lock: true\r\nnetwork.host: 127.0.0.1,10.200.x.x\r\nhttp.port: 8089\r\nbootstrap.seccomp: false\r\ndiscovery.zen.ping.unicast.hosts: [ esm1,esm2,esm3,esm4 ]\r\ndiscovery.zen.minimum_master_nodes: 3\r\ndiscovery.zen.master_election.ignore_non_master_pings: true\r\ndiscovery.zen.fd.ping_timeout: 120s\r\naction.destructive_requires_name: true\r\ncluster.routing.allocation.same_shard.host: true\r\nindices.fielddata.cache.size: 20%\r\nindices.breaker.fielddata.limit: 30%\r\nindices.breaker.request.limit: 30%\r\ncluster.routing.allocation.cluster_concurrent_rebalance: 4\r\nthread_pool.bulk.queue_size: 5000\r\ndiscovery.zen.ping_timeout: 6s\r\ndiscovery.zen.commit_timeout: 60s\r\nxpack.security.authc.realms.native.type: native\r\nxpack.security.authc.realms.native.order: 0\r\nxpack.security.authc.realms.active_directory.type: active_directory\r\nxpack.security.authc.realms.active_directory.order: 1\r\nxpack.security.authc.realms.active_directory.domain_name: xxx.xx.xxxx.com\r\nxpack.security.authc.realms.active_directory.url: ldaps://xxxx.xxxx.xxx.com:636\r\nxpack.security.authc.realms.active_directory.ssl.certificate: \"/etc/elasticsearch/x-pack/esc.cert.cert\"\r\nxpack.security.authc.realms.active_directory.ssl.key_passphrase: elastic\r\nxpack.security.authc.realms.active_directory.ssl.key: \"/etc/elasticsearch/x-pack/esc.cert.key\"\r\nxpack.security.authc.realms.active_directory.ssl.verification_mode: none\r\nxpack.security.authc.realms.active_directory.unmapped_groups_as_roles: true\r\nxpack.security.authc.realms.active_directory.timeout.tcp_connect: 30s\r\nxpack.security.authc.realms.active_directory.timeout.tcp_read: 30s\r\nxpack.security.authc.realms.active_directory.timeout.ldap_search: 30s\r\n\r\n\r\n\r\n**Steps to reproduce**:\r\n Login to Kibana or ES co-ordinator node with LDAP user credentials fails due to the timeout issue. \r\n\r\n**Provide logs (if relevant)**:\r\n\r\nLogs seen in the Elastic Co-ordinator nodes \r\n\r\n[2017-07-10T13:19:40,048][WARN ][o.e.x.s.a.AuthenticationService] [10.203.3.174] Authentication to realm active_directory failed - authenticate failed (Caused by LDAPException(resultCode=91 (connect error), errorMessage='An error occurred while attempting to connect to server xxx.xxx.xxxx.com:636:  java.io.IOException: LDAPException(resultCode=91 (connect error), errorMessage='Unable to establish a connection to server xxx.xxx.xxx.com/10.6.39.94:636 within the configured timeout of 30000 milliseconds.')'))\r\n","closed_by":{"login":"spinscale","id":667544,"node_id":"MDQ6VXNlcjY2NzU0NA==","avatar_url":"https://avatars2.githubusercontent.com/u/667544?v=4","gravatar_id":"","url":"https://api.github.com/users/spinscale","html_url":"https://github.com/spinscale","followers_url":"https://api.github.com/users/spinscale/followers","following_url":"https://api.github.com/users/spinscale/following{/other_user}","gists_url":"https://api.github.com/users/spinscale/gists{/gist_id}","starred_url":"https://api.github.com/users/spinscale/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/spinscale/subscriptions","organizations_url":"https://api.github.com/users/spinscale/orgs","repos_url":"https://api.github.com/users/spinscale/repos","events_url":"https://api.github.com/users/spinscale/events{/privacy}","received_events_url":"https://api.github.com/users/spinscale/received_events","type":"User","site_admin":false},"performed_via_github_app":null}