{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/28400","repository_url":"https://api.github.com/repos/elastic/elasticsearch","labels_url":"https://api.github.com/repos/elastic/elasticsearch/issues/28400/labels{/name}","comments_url":"https://api.github.com/repos/elastic/elasticsearch/issues/28400/comments","events_url":"https://api.github.com/repos/elastic/elasticsearch/issues/28400/events","html_url":"https://github.com/elastic/elasticsearch/issues/28400","id":291963673,"node_id":"MDU6SXNzdWUyOTE5NjM2NzM=","number":28400,"title":"Cluster does not report the exact issue","user":{"login":"cemremengu","id":1297759,"node_id":"MDQ6VXNlcjEyOTc3NTk=","avatar_url":"https://avatars0.githubusercontent.com/u/1297759?v=4","gravatar_id":"","url":"https://api.github.com/users/cemremengu","html_url":"https://github.com/cemremengu","followers_url":"https://api.github.com/users/cemremengu/followers","following_url":"https://api.github.com/users/cemremengu/following{/other_user}","gists_url":"https://api.github.com/users/cemremengu/gists{/gist_id}","starred_url":"https://api.github.com/users/cemremengu/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/cemremengu/subscriptions","organizations_url":"https://api.github.com/users/cemremengu/orgs","repos_url":"https://api.github.com/users/cemremengu/repos","events_url":"https://api.github.com/users/cemremengu/events{/privacy}","received_events_url":"https://api.github.com/users/cemremengu/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2018-01-26T16:51:07Z","updated_at":"2018-01-27T18:47:24Z","closed_at":"2018-01-27T18:47:24Z","author_association":"NONE","active_lock_reason":null,"body":"Using `docker.elastic.co/elasticsearch/elasticsearch:6.1.2`.\r\n\r\nI have a cluster consisting of 2 nodes with `discovery.zen.minimum_master_nodes=2`. Node 2 goes down and when try to execute a query on Node 1 via http, I begin to get a login popup followed by an authentication exception.\r\n\r\nIf I cancel login popup, it says `Security index is not on the current version - the native realm will not be operational until the upgrade API is run on the security index` which is (I think) irrelevant. \r\n\r\nOf course required monitoring steps should be taken in order to detect such a problem but it would be nice if it said, at least, `cluster inoperable` instead of some misleading error message.","closed_by":{"login":"bleskes","id":1006375,"node_id":"MDQ6VXNlcjEwMDYzNzU=","avatar_url":"https://avatars1.githubusercontent.com/u/1006375?v=4","gravatar_id":"","url":"https://api.github.com/users/bleskes","html_url":"https://github.com/bleskes","followers_url":"https://api.github.com/users/bleskes/followers","following_url":"https://api.github.com/users/bleskes/following{/other_user}","gists_url":"https://api.github.com/users/bleskes/gists{/gist_id}","starred_url":"https://api.github.com/users/bleskes/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/bleskes/subscriptions","organizations_url":"https://api.github.com/users/bleskes/orgs","repos_url":"https://api.github.com/users/bleskes/repos","events_url":"https://api.github.com/users/bleskes/events{/privacy}","received_events_url":"https://api.github.com/users/bleskes/received_events","type":"User","site_admin":false},"performed_via_github_app":null}