[{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/695994494","html_url":"https://github.com/elastic/elasticsearch/issues/62676#issuecomment-695994494","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/62676","id":695994494,"node_id":"MDEyOklzc3VlQ29tbWVudDY5NTk5NDQ5NA==","user":{"login":"DaveCTurner","id":5058284,"node_id":"MDQ6VXNlcjUwNTgyODQ=","avatar_url":"https://avatars3.githubusercontent.com/u/5058284?v=4","gravatar_id":"","url":"https://api.github.com/users/DaveCTurner","html_url":"https://github.com/DaveCTurner","followers_url":"https://api.github.com/users/DaveCTurner/followers","following_url":"https://api.github.com/users/DaveCTurner/following{/other_user}","gists_url":"https://api.github.com/users/DaveCTurner/gists{/gist_id}","starred_url":"https://api.github.com/users/DaveCTurner/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/DaveCTurner/subscriptions","organizations_url":"https://api.github.com/users/DaveCTurner/orgs","repos_url":"https://api.github.com/users/DaveCTurner/repos","events_url":"https://api.github.com/users/DaveCTurner/events{/privacy}","received_events_url":"https://api.github.com/users/DaveCTurner/received_events","type":"User","site_admin":false},"created_at":"2020-09-21T09:09:46Z","updated_at":"2020-09-21T09:09:46Z","author_association":"CONTRIBUTOR","body":"This doesn't look to be the complete picture @kkewwei and certainly not enough for us to reproduce it. Requests always eventually receive a response, even if it's an error indicating that a connection was dropped, so the client likely wasn't blocked forever. How long did you wait?\r\n\r\nWhich node was dropped from the cluster? In particular, was it the coordinating node that this client was using, or was it a different node? Did it join the cluster again? Can you share the logs from the cluster?\r\n\r\nHave you configured your [TCP retransmission timeout](https://www.elastic.co/guide/en/elasticsearch/reference/current/system-config-tcpretries.html) appropriately? The defaults are quite slow to detect a connection drop on Linux.\r\n\r\nAre you using the deprecated transport client here?","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/695994587","html_url":"https://github.com/elastic/elasticsearch/issues/62676#issuecomment-695994587","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/62676","id":695994587,"node_id":"MDEyOklzc3VlQ29tbWVudDY5NTk5NDU4Nw==","user":{"login":"elasticmachine","id":15837671,"node_id":"MDQ6VXNlcjE1ODM3Njcx","avatar_url":"https://avatars3.githubusercontent.com/u/15837671?v=4","gravatar_id":"","url":"https://api.github.com/users/elasticmachine","html_url":"https://github.com/elasticmachine","followers_url":"https://api.github.com/users/elasticmachine/followers","following_url":"https://api.github.com/users/elasticmachine/following{/other_user}","gists_url":"https://api.github.com/users/elasticmachine/gists{/gist_id}","starred_url":"https://api.github.com/users/elasticmachine/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/elasticmachine/subscriptions","organizations_url":"https://api.github.com/users/elasticmachine/orgs","repos_url":"https://api.github.com/users/elasticmachine/repos","events_url":"https://api.github.com/users/elasticmachine/events{/privacy}","received_events_url":"https://api.github.com/users/elasticmachine/received_events","type":"User","site_admin":false},"created_at":"2020-09-21T09:09:59Z","updated_at":"2020-09-21T09:09:59Z","author_association":"COLLABORATOR","body":"Pinging @elastic/es-distributed (:Distributed/Network)","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/696096897","html_url":"https://github.com/elastic/elasticsearch/issues/62676#issuecomment-696096897","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/62676","id":696096897,"node_id":"MDEyOklzc3VlQ29tbWVudDY5NjA5Njg5Nw==","user":{"login":"kkewwei","id":16730433,"node_id":"MDQ6VXNlcjE2NzMwNDMz","avatar_url":"https://avatars1.githubusercontent.com/u/16730433?v=4","gravatar_id":"","url":"https://api.github.com/users/kkewwei","html_url":"https://github.com/kkewwei","followers_url":"https://api.github.com/users/kkewwei/followers","following_url":"https://api.github.com/users/kkewwei/following{/other_user}","gists_url":"https://api.github.com/users/kkewwei/gists{/gist_id}","starred_url":"https://api.github.com/users/kkewwei/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/kkewwei/subscriptions","organizations_url":"https://api.github.com/users/kkewwei/orgs","repos_url":"https://api.github.com/users/kkewwei/repos","events_url":"https://api.github.com/users/kkewwei/events{/privacy}","received_events_url":"https://api.github.com/users/kkewwei/received_events","type":"User","site_admin":false},"created_at":"2020-09-21T12:58:30Z","updated_at":"2020-09-21T13:07:53Z","author_association":"CONTRIBUTOR","body":"Dropped node is a data node. Because of hardware malfunction, the dropped node doesn't rejoin the cluster. net.ipv4.tcp_retries2 is default value(15). The write process is blocked more than two days before I restart it, \r\nthe logs from master is as follow:\r\n```\r\n[2020-09-18T17:57:22,309][INFO ][o.e.c.s.ClusterApplierService] [maser] removed {{node1}{XM906CD1RjGPaRju_Wti1w}{MfFAX4EzSWGxNuIIxRLElQ}{10.xx.xx.22}{10.xx.xx22:9300}{dilrt}{ml.machine_memory=135299469312, rack=gha, ml.max_open_jobs=20, xpack.installed=true, transform.node=true}}, term: 1, version: 7593, reason: ApplyCommitRequest{term=1, version=7593, sourceNode={master1}{_SfHFfRpTimHlhUFJWrMgQ}{1B8FnKs8RnqPvCmqaRgoiA}{10.xx.xx.242}{10.xx.xx.242:9300}{ilmr}{ml.machine_memory=16644907008, rack=gha, ml.max_open_jobs=20, xpack.installed=true, transform.node=false}}\r\n```\r\nI don't see any other wrong.\r\nAccording to the phenomenon, it seems that:client sends bulk request to the data node, and data node has received the request correctly, then it processes the bulk request which costs much time, During the process, the data node goes offline. Because of no except from the data node, client will not be able to perceive that the date node has hung up. \r\n\r\nBecauese of cluster upgrade, I continue to use the transport client and have no time to replace with highlevel client.","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/696117720","html_url":"https://github.com/elastic/elasticsearch/issues/62676#issuecomment-696117720","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/62676","id":696117720,"node_id":"MDEyOklzc3VlQ29tbWVudDY5NjExNzcyMA==","user":{"login":"DaveCTurner","id":5058284,"node_id":"MDQ6VXNlcjUwNTgyODQ=","avatar_url":"https://avatars3.githubusercontent.com/u/5058284?v=4","gravatar_id":"","url":"https://api.github.com/users/DaveCTurner","html_url":"https://github.com/DaveCTurner","followers_url":"https://api.github.com/users/DaveCTurner/followers","following_url":"https://api.github.com/users/DaveCTurner/following{/other_user}","gists_url":"https://api.github.com/users/DaveCTurner/gists{/gist_id}","starred_url":"https://api.github.com/users/DaveCTurner/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/DaveCTurner/subscriptions","organizations_url":"https://api.github.com/users/DaveCTurner/orgs","repos_url":"https://api.github.com/users/DaveCTurner/repos","events_url":"https://api.github.com/users/DaveCTurner/events{/privacy}","received_events_url":"https://api.github.com/users/DaveCTurner/received_events","type":"User","site_admin":false},"created_at":"2020-09-21T13:33:38Z","updated_at":"2020-09-21T13:33:38Z","author_association":"CONTRIBUTOR","body":"Did the client send the bulk request _directly_ to the faulty data node, or did it send it to a different coordinating node?\r\n\r\nWhen you say that the data node was \"offline\" do you mean it was still running and trying unsuccessfully to re-join the cluster for two whole days?","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/696151007","html_url":"https://github.com/elastic/elasticsearch/issues/62676#issuecomment-696151007","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/62676","id":696151007,"node_id":"MDEyOklzc3VlQ29tbWVudDY5NjE1MTAwNw==","user":{"login":"kkewwei","id":16730433,"node_id":"MDQ6VXNlcjE2NzMwNDMz","avatar_url":"https://avatars1.githubusercontent.com/u/16730433?v=4","gravatar_id":"","url":"https://api.github.com/users/kkewwei","html_url":"https://github.com/kkewwei","followers_url":"https://api.github.com/users/kkewwei/followers","following_url":"https://api.github.com/users/kkewwei/following{/other_user}","gists_url":"https://api.github.com/users/kkewwei/gists{/gist_id}","starred_url":"https://api.github.com/users/kkewwei/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/kkewwei/subscriptions","organizations_url":"https://api.github.com/users/kkewwei/orgs","repos_url":"https://api.github.com/users/kkewwei/repos","events_url":"https://api.github.com/users/kkewwei/events{/privacy}","received_events_url":"https://api.github.com/users/kkewwei/received_events","type":"User","site_admin":false},"created_at":"2020-09-21T14:25:50Z","updated_at":"2020-09-21T14:25:50Z","author_association":"CONTRIBUTOR","body":"We don't set  coordinating node separately, any node can be coordinating node. Data node was \"offline\" mean the machine went down due to hardware problems, and we can't ping it.\r\n\r\nBecause of going offline, the data node can't response exception to the client, the netty channel in client might be disconnected from the data node after a few minutes, but the bulk request from the client will be hung forever.","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/696163579","html_url":"https://github.com/elastic/elasticsearch/issues/62676#issuecomment-696163579","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/62676","id":696163579,"node_id":"MDEyOklzc3VlQ29tbWVudDY5NjE2MzU3OQ==","user":{"login":"kkewwei","id":16730433,"node_id":"MDQ6VXNlcjE2NzMwNDMz","avatar_url":"https://avatars1.githubusercontent.com/u/16730433?v=4","gravatar_id":"","url":"https://api.github.com/users/kkewwei","html_url":"https://github.com/kkewwei","followers_url":"https://api.github.com/users/kkewwei/followers","following_url":"https://api.github.com/users/kkewwei/following{/other_user}","gists_url":"https://api.github.com/users/kkewwei/gists{/gist_id}","starred_url":"https://api.github.com/users/kkewwei/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/kkewwei/subscriptions","organizations_url":"https://api.github.com/users/kkewwei/orgs","repos_url":"https://api.github.com/users/kkewwei/repos","events_url":"https://api.github.com/users/kkewwei/events{/privacy}","received_events_url":"https://api.github.com/users/kkewwei/received_events","type":"User","site_admin":false},"created_at":"2020-09-21T14:46:22Z","updated_at":"2020-09-21T14:46:36Z","author_association":"CONTRIBUTOR","body":"It seems that client doesn't  take into account ongoing requests when closing the channel.","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/696189580","html_url":"https://github.com/elastic/elasticsearch/issues/62676#issuecomment-696189580","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/62676","id":696189580,"node_id":"MDEyOklzc3VlQ29tbWVudDY5NjE4OTU4MA==","user":{"login":"DaveCTurner","id":5058284,"node_id":"MDQ6VXNlcjUwNTgyODQ=","avatar_url":"https://avatars3.githubusercontent.com/u/5058284?v=4","gravatar_id":"","url":"https://api.github.com/users/DaveCTurner","html_url":"https://github.com/DaveCTurner","followers_url":"https://api.github.com/users/DaveCTurner/followers","following_url":"https://api.github.com/users/DaveCTurner/following{/other_user}","gists_url":"https://api.github.com/users/DaveCTurner/gists{/gist_id}","starred_url":"https://api.github.com/users/DaveCTurner/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/DaveCTurner/subscriptions","organizations_url":"https://api.github.com/users/DaveCTurner/orgs","repos_url":"https://api.github.com/users/DaveCTurner/repos","events_url":"https://api.github.com/users/DaveCTurner/events{/privacy}","received_events_url":"https://api.github.com/users/DaveCTurner/received_events","type":"User","site_admin":false},"created_at":"2020-09-21T15:28:58Z","updated_at":"2020-09-21T15:28:58Z","author_association":"CONTRIBUTOR","body":"> It seems that client doesn't take into account ongoing requests when closing the channel.\r\n\r\nThat is very surprising. It should be returning a `NodeDisconnectedException` to all outstanding requests on a channel with the code here:\r\n\r\nhttps://github.com/elastic/elasticsearch/blob/52ad5842a950332201efe852472c4f1b4d40a6ff/server/src/main/java/org/elasticsearch/transport/TransportService.java#L1034-L1035\r\n\r\nHow have you determined that this isn't happening in your case?","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/696690456","html_url":"https://github.com/elastic/elasticsearch/issues/62676#issuecomment-696690456","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/62676","id":696690456,"node_id":"MDEyOklzc3VlQ29tbWVudDY5NjY5MDQ1Ng==","user":{"login":"kkewwei","id":16730433,"node_id":"MDQ6VXNlcjE2NzMwNDMz","avatar_url":"https://avatars1.githubusercontent.com/u/16730433?v=4","gravatar_id":"","url":"https://api.github.com/users/kkewwei","html_url":"https://github.com/kkewwei","followers_url":"https://api.github.com/users/kkewwei/followers","following_url":"https://api.github.com/users/kkewwei/following{/other_user}","gists_url":"https://api.github.com/users/kkewwei/gists{/gist_id}","starred_url":"https://api.github.com/users/kkewwei/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/kkewwei/subscriptions","organizations_url":"https://api.github.com/users/kkewwei/orgs","repos_url":"https://api.github.com/users/kkewwei/repos","events_url":"https://api.github.com/users/kkewwei/events{/privacy}","received_events_url":"https://api.github.com/users/kkewwei/received_events","type":"User","site_admin":false},"created_at":"2020-09-22T12:31:48Z","updated_at":"2020-09-22T12:32:41Z","author_association":"CONTRIBUTOR","body":"I see the code: https://github.com/elastic/elasticsearch/blob/52ad5842a950332201efe852472c4f1b4d40a6ff/server/src/main/java/org/elasticsearch/transport/TransportService.java#L1034-L1035\r\n\r\nFor bulk request, it only comes here:\r\nhttps://github.com/elastic/elasticsearch/blob/52ad5842a950332201efe852472c4f1b4d40a6ff/server/src/main/java/org/elasticsearch/client/transport/TransportClientNodesService.java#L297\r\nES just pick another node out to resend the bulk request, and not interrupt the lock.\r\n ","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/696730906","html_url":"https://github.com/elastic/elasticsearch/issues/62676#issuecomment-696730906","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/62676","id":696730906,"node_id":"MDEyOklzc3VlQ29tbWVudDY5NjczMDkwNg==","user":{"login":"DaveCTurner","id":5058284,"node_id":"MDQ6VXNlcjUwNTgyODQ=","avatar_url":"https://avatars3.githubusercontent.com/u/5058284?v=4","gravatar_id":"","url":"https://api.github.com/users/DaveCTurner","html_url":"https://github.com/DaveCTurner","followers_url":"https://api.github.com/users/DaveCTurner/followers","following_url":"https://api.github.com/users/DaveCTurner/following{/other_user}","gists_url":"https://api.github.com/users/DaveCTurner/gists{/gist_id}","starred_url":"https://api.github.com/users/DaveCTurner/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/DaveCTurner/subscriptions","organizations_url":"https://api.github.com/users/DaveCTurner/orgs","repos_url":"https://api.github.com/users/DaveCTurner/repos","events_url":"https://api.github.com/users/DaveCTurner/events{/privacy}","received_events_url":"https://api.github.com/users/DaveCTurner/received_events","type":"User","site_admin":false},"created_at":"2020-09-22T13:43:42Z","updated_at":"2020-09-22T13:43:42Z","author_association":"CONTRIBUTOR","body":"Sure, but that only tries once per node, and each attempt will receive some kind of response (even if just a `NodeDisconnectedException`) so this should still eventually complete the request.","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/696739734","html_url":"https://github.com/elastic/elasticsearch/issues/62676#issuecomment-696739734","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/62676","id":696739734,"node_id":"MDEyOklzc3VlQ29tbWVudDY5NjczOTczNA==","user":{"login":"kkewwei","id":16730433,"node_id":"MDQ6VXNlcjE2NzMwNDMz","avatar_url":"https://avatars1.githubusercontent.com/u/16730433?v=4","gravatar_id":"","url":"https://api.github.com/users/kkewwei","html_url":"https://github.com/kkewwei","followers_url":"https://api.github.com/users/kkewwei/followers","following_url":"https://api.github.com/users/kkewwei/following{/other_user}","gists_url":"https://api.github.com/users/kkewwei/gists{/gist_id}","starred_url":"https://api.github.com/users/kkewwei/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/kkewwei/subscriptions","organizations_url":"https://api.github.com/users/kkewwei/orgs","repos_url":"https://api.github.com/users/kkewwei/repos","events_url":"https://api.github.com/users/kkewwei/events{/privacy}","received_events_url":"https://api.github.com/users/kkewwei/received_events","type":"User","site_admin":false},"created_at":"2020-09-22T13:57:57Z","updated_at":"2020-09-22T14:02:40Z","author_association":"CONTRIBUTOR","body":"The request can be eventually completed, but we don't unlock the ReentrantLock and CountDownLatch by interrupt it, it can't be released by itself.\r\n\r\nBy the way, we set concurrent to be 0, so there only has one thread in BulkProcessor to send bulk request, if the only one write thread is blocked, the process will be blocked to write.","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/696748670","html_url":"https://github.com/elastic/elasticsearch/issues/62676#issuecomment-696748670","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/62676","id":696748670,"node_id":"MDEyOklzc3VlQ29tbWVudDY5Njc0ODY3MA==","user":{"login":"DaveCTurner","id":5058284,"node_id":"MDQ6VXNlcjUwNTgyODQ=","avatar_url":"https://avatars3.githubusercontent.com/u/5058284?v=4","gravatar_id":"","url":"https://api.github.com/users/DaveCTurner","html_url":"https://github.com/DaveCTurner","followers_url":"https://api.github.com/users/DaveCTurner/followers","following_url":"https://api.github.com/users/DaveCTurner/following{/other_user}","gists_url":"https://api.github.com/users/DaveCTurner/gists{/gist_id}","starred_url":"https://api.github.com/users/DaveCTurner/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/DaveCTurner/subscriptions","organizations_url":"https://api.github.com/users/DaveCTurner/orgs","repos_url":"https://api.github.com/users/DaveCTurner/repos","events_url":"https://api.github.com/users/DaveCTurner/events{/privacy}","received_events_url":"https://api.github.com/users/DaveCTurner/received_events","type":"User","site_admin":false},"created_at":"2020-09-22T14:12:30Z","updated_at":"2020-09-22T14:12:30Z","author_association":"CONTRIBUTOR","body":"I'm still not following. When the request completes, the latch is unlocked:\r\n\r\nhttps://github.com/elastic/elasticsearch/blob/ecd033bea62489e70c60763cfc117d0b96534fa0/server/src/main/java/org/elasticsearch/action/bulk/BulkRequestHandler.java#L74\r\n\r\n(possibly after some more retries, according to your `BackoffPolicy`, but still only finitely many of them, so in any case it should return eventually)","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/696829261","html_url":"https://github.com/elastic/elasticsearch/issues/62676#issuecomment-696829261","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/62676","id":696829261,"node_id":"MDEyOklzc3VlQ29tbWVudDY5NjgyOTI2MQ==","user":{"login":"kkewwei","id":16730433,"node_id":"MDQ6VXNlcjE2NzMwNDMz","avatar_url":"https://avatars1.githubusercontent.com/u/16730433?v=4","gravatar_id":"","url":"https://api.github.com/users/kkewwei","html_url":"https://github.com/kkewwei","followers_url":"https://api.github.com/users/kkewwei/followers","following_url":"https://api.github.com/users/kkewwei/following{/other_user}","gists_url":"https://api.github.com/users/kkewwei/gists{/gist_id}","starred_url":"https://api.github.com/users/kkewwei/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/kkewwei/subscriptions","organizations_url":"https://api.github.com/users/kkewwei/orgs","repos_url":"https://api.github.com/users/kkewwei/repos","events_url":"https://api.github.com/users/kkewwei/events{/privacy}","received_events_url":"https://api.github.com/users/kkewwei/received_events","type":"User","site_admin":false},"created_at":"2020-09-22T16:21:02Z","updated_at":"2020-09-22T16:21:40Z","author_association":"CONTRIBUTOR","body":"I see the code will be executed after in `onResponse()` or after in `onFailure()`\r\nhttps://github.com/elastic/elasticsearch/blob/ecd033bea62489e70c60763cfc117d0b96534fa0/server/src/main/java/org/elasticsearch/action/bulk/BulkRequestHandler.java#L74\r\n\r\n`onResponse()` will be executed after the client receives the BulkResponse. `onFailure()` will be executed after failing to send the bulk request. The situation we face is that the bulk request has been sent successfully, `onFailure()` will not be executed, but as the data node went offline, the client cannot receive the response, so `onResponse()` will not be executed.\r\nSo `latch.countDown(); `will never be executed.\r\n","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/696849124","html_url":"https://github.com/elastic/elasticsearch/issues/62676#issuecomment-696849124","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/62676","id":696849124,"node_id":"MDEyOklzc3VlQ29tbWVudDY5Njg0OTEyNA==","user":{"login":"DaveCTurner","id":5058284,"node_id":"MDQ6VXNlcjUwNTgyODQ=","avatar_url":"https://avatars3.githubusercontent.com/u/5058284?v=4","gravatar_id":"","url":"https://api.github.com/users/DaveCTurner","html_url":"https://github.com/DaveCTurner","followers_url":"https://api.github.com/users/DaveCTurner/followers","following_url":"https://api.github.com/users/DaveCTurner/following{/other_user}","gists_url":"https://api.github.com/users/DaveCTurner/gists{/gist_id}","starred_url":"https://api.github.com/users/DaveCTurner/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/DaveCTurner/subscriptions","organizations_url":"https://api.github.com/users/DaveCTurner/orgs","repos_url":"https://api.github.com/users/DaveCTurner/repos","events_url":"https://api.github.com/users/DaveCTurner/events{/privacy}","received_events_url":"https://api.github.com/users/DaveCTurner/received_events","type":"User","site_admin":false},"created_at":"2020-09-22T16:56:47Z","updated_at":"2020-09-22T16:56:47Z","author_association":"CONTRIBUTOR","body":"No, `onFailure()` is also executed when the request is sent successfully and then fails exceptionally (e.g. with a `NodeDisconnectedException`). At least that's how `client::bulk` behaves -- if you're using a different `consumer` with your `BulkProcessor` then you must ensure it behaves the same.","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/696876208","html_url":"https://github.com/elastic/elasticsearch/issues/62676#issuecomment-696876208","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/62676","id":696876208,"node_id":"MDEyOklzc3VlQ29tbWVudDY5Njg3NjIwOA==","user":{"login":"DaveCTurner","id":5058284,"node_id":"MDQ6VXNlcjUwNTgyODQ=","avatar_url":"https://avatars3.githubusercontent.com/u/5058284?v=4","gravatar_id":"","url":"https://api.github.com/users/DaveCTurner","html_url":"https://github.com/DaveCTurner","followers_url":"https://api.github.com/users/DaveCTurner/followers","following_url":"https://api.github.com/users/DaveCTurner/following{/other_user}","gists_url":"https://api.github.com/users/DaveCTurner/gists{/gist_id}","starred_url":"https://api.github.com/users/DaveCTurner/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/DaveCTurner/subscriptions","organizations_url":"https://api.github.com/users/DaveCTurner/orgs","repos_url":"https://api.github.com/users/DaveCTurner/repos","events_url":"https://api.github.com/users/DaveCTurner/events{/privacy}","received_events_url":"https://api.github.com/users/DaveCTurner/received_events","type":"User","site_admin":false},"created_at":"2020-09-22T17:45:36Z","updated_at":"2020-09-22T19:33:23Z","author_association":"CONTRIBUTOR","body":"We already covered this in https://github.com/elastic/elasticsearch/issues/62676#issuecomment-696730906, but in more detail `callback.doWithNode(getNode(i), this)` passes `this` (i.e. a `RetryListener`) as its listener, which means that it will call `RetryListener#onFailure` again if the retry also fails (whether immediately or after successfully sending the request). It keeps doing this until `i >= nodes.size()` at which point it gives up and notifies the outer listener.\r\n\r\n(edit: this is in response to a comment that has since been deleted questioning whether `RetryListener#onFailure` might fail to notify the outer listener or not; @kkewwei please don't do that -- your questions are helping us to rule out locations for a possible bug, and altering the conversation makes it much much harder to follow)","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/697096168","html_url":"https://github.com/elastic/elasticsearch/issues/62676#issuecomment-697096168","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/62676","id":697096168,"node_id":"MDEyOklzc3VlQ29tbWVudDY5NzA5NjE2OA==","user":{"login":"kkewwei","id":16730433,"node_id":"MDQ6VXNlcjE2NzMwNDMz","avatar_url":"https://avatars1.githubusercontent.com/u/16730433?v=4","gravatar_id":"","url":"https://api.github.com/users/kkewwei","html_url":"https://github.com/kkewwei","followers_url":"https://api.github.com/users/kkewwei/followers","following_url":"https://api.github.com/users/kkewwei/following{/other_user}","gists_url":"https://api.github.com/users/kkewwei/gists{/gist_id}","starred_url":"https://api.github.com/users/kkewwei/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/kkewwei/subscriptions","organizations_url":"https://api.github.com/users/kkewwei/orgs","repos_url":"https://api.github.com/users/kkewwei/repos","events_url":"https://api.github.com/users/kkewwei/events{/privacy}","received_events_url":"https://api.github.com/users/kkewwei/received_events","type":"User","site_admin":false},"created_at":"2020-09-23T02:41:05Z","updated_at":"2020-09-23T03:31:27Z","author_association":"CONTRIBUTOR","body":"once returning a NodeDisconnectedException, the code will come to here: \r\nhttps://github.com/elastic/elasticsearch/blob/52ad5842a950332201efe852472c4f1b4d40a6ff/server/src/main/java/org/elasticsearch/client/transport/TransportClientNodesService.java#L288\r\n\r\nyes, you are right,  in `RetryListener` onFailure() may be executed, but on the one of the basic:\r\n1. there will be no available node to retry.\r\n2. executing `callback.doWithNode(getNode(i), this);` and  throws exception\r\n3. the exception is not `ConnectTransportException`\r\nhttps://github.com/elastic/elasticsearch/blob/52ad5842a950332201efe852472c4f1b4d40a6ff/server/src/main/java/org/elasticsearch/client/transport/TransportClientNodesService.java#L288\r\n\r\nOnce `callback.doWithNode(getNode(i), this);` is executed successfully, `onFailure()`will not be executed. This is the scene I described.\r\n\r\n(It's the comment I deleted, I wanted to give a more professional answer, I will not do it again.)\r\n","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/697105695","html_url":"https://github.com/elastic/elasticsearch/issues/62676#issuecomment-697105695","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/62676","id":697105695,"node_id":"MDEyOklzc3VlQ29tbWVudDY5NzEwNTY5NQ==","user":{"login":"kkewwei","id":16730433,"node_id":"MDQ6VXNlcjE2NzMwNDMz","avatar_url":"https://avatars1.githubusercontent.com/u/16730433?v=4","gravatar_id":"","url":"https://api.github.com/users/kkewwei","html_url":"https://github.com/kkewwei","followers_url":"https://api.github.com/users/kkewwei/followers","following_url":"https://api.github.com/users/kkewwei/following{/other_user}","gists_url":"https://api.github.com/users/kkewwei/gists{/gist_id}","starred_url":"https://api.github.com/users/kkewwei/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/kkewwei/subscriptions","organizations_url":"https://api.github.com/users/kkewwei/orgs","repos_url":"https://api.github.com/users/kkewwei/repos","events_url":"https://api.github.com/users/kkewwei/events{/privacy}","received_events_url":"https://api.github.com/users/kkewwei/received_events","type":"User","site_admin":false},"created_at":"2020-09-23T03:08:39Z","updated_at":"2020-09-23T03:18:37Z","author_association":"CONTRIBUTOR","body":"> It keeps doing this until i >= nodes.size() at which point it gives up and notifies the outer listener.\r\n\r\nI Still have doubt, only if all nodes fail to send bulk request, and will  notifies the outer listener, then the `listener.onFailure` can be executed. but if `callback.doWithNode(getNode(i), this)` is successful on a node, it will not execute `listener.onFailure(inner);` ","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/697173372","html_url":"https://github.com/elastic/elasticsearch/issues/62676#issuecomment-697173372","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/62676","id":697173372,"node_id":"MDEyOklzc3VlQ29tbWVudDY5NzE3MzM3Mg==","user":{"login":"DaveCTurner","id":5058284,"node_id":"MDQ6VXNlcjUwNTgyODQ=","avatar_url":"https://avatars3.githubusercontent.com/u/5058284?v=4","gravatar_id":"","url":"https://api.github.com/users/DaveCTurner","html_url":"https://github.com/DaveCTurner","followers_url":"https://api.github.com/users/DaveCTurner/followers","following_url":"https://api.github.com/users/DaveCTurner/following{/other_user}","gists_url":"https://api.github.com/users/DaveCTurner/gists{/gist_id}","starred_url":"https://api.github.com/users/DaveCTurner/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/DaveCTurner/subscriptions","organizations_url":"https://api.github.com/users/DaveCTurner/orgs","repos_url":"https://api.github.com/users/DaveCTurner/repos","events_url":"https://api.github.com/users/DaveCTurner/events{/privacy}","received_events_url":"https://api.github.com/users/DaveCTurner/received_events","type":"User","site_admin":false},"created_at":"2020-09-23T06:58:12Z","updated_at":"2020-09-23T06:58:12Z","author_association":"CONTRIBUTOR","body":"> if `callback.doWithNode(getNode(i), this)` is successful on a node, it will not execute `listener.onFailure(inner);` \r\n\r\nYes that is right, if it's successful then it executes the `onResponse()` method of the listener instead. In either case the latch is released.","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/698889648","html_url":"https://github.com/elastic/elasticsearch/issues/62676#issuecomment-698889648","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/62676","id":698889648,"node_id":"MDEyOklzc3VlQ29tbWVudDY5ODg4OTY0OA==","user":{"login":"kkewwei","id":16730433,"node_id":"MDQ6VXNlcjE2NzMwNDMz","avatar_url":"https://avatars1.githubusercontent.com/u/16730433?v=4","gravatar_id":"","url":"https://api.github.com/users/kkewwei","html_url":"https://github.com/kkewwei","followers_url":"https://api.github.com/users/kkewwei/followers","following_url":"https://api.github.com/users/kkewwei/following{/other_user}","gists_url":"https://api.github.com/users/kkewwei/gists{/gist_id}","starred_url":"https://api.github.com/users/kkewwei/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/kkewwei/subscriptions","organizations_url":"https://api.github.com/users/kkewwei/orgs","repos_url":"https://api.github.com/users/kkewwei/repos","events_url":"https://api.github.com/users/kkewwei/events{/privacy}","received_events_url":"https://api.github.com/users/kkewwei/received_events","type":"User","site_admin":false},"created_at":"2020-09-25T12:01:29Z","updated_at":"2020-09-25T12:13:31Z","author_association":"CONTRIBUTOR","body":"yes, you are right, code is ok.  I will close the issue, very thank you for your explain. Maybe there has other reason, I will go on try to find it.","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/725338680","html_url":"https://github.com/elastic/elasticsearch/issues/62676#issuecomment-725338680","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/62676","id":725338680,"node_id":"MDEyOklzc3VlQ29tbWVudDcyNTMzODY4MA==","user":{"login":"kkewwei","id":16730433,"node_id":"MDQ6VXNlcjE2NzMwNDMz","avatar_url":"https://avatars1.githubusercontent.com/u/16730433?v=4","gravatar_id":"","url":"https://api.github.com/users/kkewwei","html_url":"https://github.com/kkewwei","followers_url":"https://api.github.com/users/kkewwei/followers","following_url":"https://api.github.com/users/kkewwei/following{/other_user}","gists_url":"https://api.github.com/users/kkewwei/gists{/gist_id}","starred_url":"https://api.github.com/users/kkewwei/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/kkewwei/subscriptions","organizations_url":"https://api.github.com/users/kkewwei/orgs","repos_url":"https://api.github.com/users/kkewwei/repos","events_url":"https://api.github.com/users/kkewwei/events{/privacy}","received_events_url":"https://api.github.com/users/kkewwei/received_events","type":"User","site_admin":false},"created_at":"2020-11-11T10:22:52Z","updated_at":"2020-11-11T10:25:25Z","author_association":"CONTRIBUTOR","body":"@DaveCTurner, Recently it occurred again, the reason is that, when the netty worker thread  in client receives the bulkResponse, it crashes because of OutOfMemoryError, so the bulkResponse is dropped, as the result, the write thread is blocked in the code `latch.countDown(); `. we use Flink sink to write to es, it seems that Flink catch the oom exception, and the jvm works well.","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/725355939","html_url":"https://github.com/elastic/elasticsearch/issues/62676#issuecomment-725355939","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/62676","id":725355939,"node_id":"MDEyOklzc3VlQ29tbWVudDcyNTM1NTkzOQ==","user":{"login":"DaveCTurner","id":5058284,"node_id":"MDQ6VXNlcjUwNTgyODQ=","avatar_url":"https://avatars3.githubusercontent.com/u/5058284?v=4","gravatar_id":"","url":"https://api.github.com/users/DaveCTurner","html_url":"https://github.com/DaveCTurner","followers_url":"https://api.github.com/users/DaveCTurner/followers","following_url":"https://api.github.com/users/DaveCTurner/following{/other_user}","gists_url":"https://api.github.com/users/DaveCTurner/gists{/gist_id}","starred_url":"https://api.github.com/users/DaveCTurner/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/DaveCTurner/subscriptions","organizations_url":"https://api.github.com/users/DaveCTurner/orgs","repos_url":"https://api.github.com/users/DaveCTurner/repos","events_url":"https://api.github.com/users/DaveCTurner/events{/privacy}","received_events_url":"https://api.github.com/users/DaveCTurner/received_events","type":"User","site_admin":false},"created_at":"2020-11-11T10:58:33Z","updated_at":"2020-11-11T10:58:42Z","author_association":"CONTRIBUTOR","body":"This is a bug in your client: you [should not catch subclasses of `java.lang.Error`](https://docs.oracle.com/en/java/javase/14/docs/api/java.base/java/lang/Error.html). There's no reasonable way to proceed after an OOME except to shut the whole JVM down.","performed_via_github_app":null}]