[{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/45918900","html_url":"https://github.com/elastic/elasticsearch/issues/6410#issuecomment-45918900","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/6410","id":45918900,"node_id":"MDEyOklzc3VlQ29tbWVudDQ1OTE4OTAw","user":{"login":"tmkujala","id":2327359,"node_id":"MDQ6VXNlcjIzMjczNTk=","avatar_url":"https://avatars1.githubusercontent.com/u/2327359?v=4","gravatar_id":"","url":"https://api.github.com/users/tmkujala","html_url":"https://github.com/tmkujala","followers_url":"https://api.github.com/users/tmkujala/followers","following_url":"https://api.github.com/users/tmkujala/following{/other_user}","gists_url":"https://api.github.com/users/tmkujala/gists{/gist_id}","starred_url":"https://api.github.com/users/tmkujala/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/tmkujala/subscriptions","organizations_url":"https://api.github.com/users/tmkujala/orgs","repos_url":"https://api.github.com/users/tmkujala/repos","events_url":"https://api.github.com/users/tmkujala/events{/privacy}","received_events_url":"https://api.github.com/users/tmkujala/received_events","type":"User","site_admin":false},"created_at":"2014-06-12T17:00:13Z","updated_at":"2014-06-12T17:00:13Z","author_association":"NONE","body":"This issue was giving me some trouble as well, saw it was fixed in the 1.1 and 1.2 branches, see #4987.\n","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/48298353","html_url":"https://github.com/elastic/elasticsearch/issues/6410#issuecomment-48298353","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/6410","id":48298353,"node_id":"MDEyOklzc3VlQ29tbWVudDQ4Mjk4MzUz","user":{"login":"TheLudd","id":557295,"node_id":"MDQ6VXNlcjU1NzI5NQ==","avatar_url":"https://avatars0.githubusercontent.com/u/557295?v=4","gravatar_id":"","url":"https://api.github.com/users/TheLudd","html_url":"https://github.com/TheLudd","followers_url":"https://api.github.com/users/TheLudd/followers","following_url":"https://api.github.com/users/TheLudd/following{/other_user}","gists_url":"https://api.github.com/users/TheLudd/gists{/gist_id}","starred_url":"https://api.github.com/users/TheLudd/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/TheLudd/subscriptions","organizations_url":"https://api.github.com/users/TheLudd/orgs","repos_url":"https://api.github.com/users/TheLudd/repos","events_url":"https://api.github.com/users/TheLudd/events{/privacy}","received_events_url":"https://api.github.com/users/TheLudd/received_events","type":"User","site_admin":false},"created_at":"2014-07-08T10:02:23Z","updated_at":"2014-07-08T10:02:23Z","author_association":"NONE","body":"@tmkujala This bug is not fixed. It is not the same as #4987. That one tackles _invalid_ index names. This one talks about performing bulk operations against indices that does not exits and where the response would be 404. This of course only occurs if you have the option `action.auto_create_index` set to false. But I experience this error as well.\n","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/48309664","html_url":"https://github.com/elastic/elasticsearch/issues/6410#issuecomment-48309664","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/6410","id":48309664,"node_id":"MDEyOklzc3VlQ29tbWVudDQ4MzA5NjY0","user":{"login":"clintongormley","id":56599,"node_id":"MDQ6VXNlcjU2NTk5","avatar_url":"https://avatars0.githubusercontent.com/u/56599?v=4","gravatar_id":"","url":"https://api.github.com/users/clintongormley","html_url":"https://github.com/clintongormley","followers_url":"https://api.github.com/users/clintongormley/followers","following_url":"https://api.github.com/users/clintongormley/following{/other_user}","gists_url":"https://api.github.com/users/clintongormley/gists{/gist_id}","starred_url":"https://api.github.com/users/clintongormley/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/clintongormley/subscriptions","organizations_url":"https://api.github.com/users/clintongormley/orgs","repos_url":"https://api.github.com/users/clintongormley/repos","events_url":"https://api.github.com/users/clintongormley/events{/privacy}","received_events_url":"https://api.github.com/users/clintongormley/received_events","type":"User","site_admin":false},"created_at":"2014-07-08T10:11:19Z","updated_at":"2014-07-08T10:11:19Z","author_association":"CONTRIBUTOR","body":"@spinscale I've confirmed that this bug still exists in master.\n","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/48438343","html_url":"https://github.com/elastic/elasticsearch/issues/6410#issuecomment-48438343","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/6410","id":48438343,"node_id":"MDEyOklzc3VlQ29tbWVudDQ4NDM4MzQz","user":{"login":"TheLudd","id":557295,"node_id":"MDQ6VXNlcjU1NzI5NQ==","avatar_url":"https://avatars0.githubusercontent.com/u/557295?v=4","gravatar_id":"","url":"https://api.github.com/users/TheLudd","html_url":"https://github.com/TheLudd","followers_url":"https://api.github.com/users/TheLudd/followers","following_url":"https://api.github.com/users/TheLudd/following{/other_user}","gists_url":"https://api.github.com/users/TheLudd/gists{/gist_id}","starred_url":"https://api.github.com/users/TheLudd/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/TheLudd/subscriptions","organizations_url":"https://api.github.com/users/TheLudd/orgs","repos_url":"https://api.github.com/users/TheLudd/repos","events_url":"https://api.github.com/users/TheLudd/events{/privacy}","received_events_url":"https://api.github.com/users/TheLudd/received_events","type":"User","site_admin":false},"created_at":"2014-07-09T07:32:02Z","updated_at":"2014-07-09T07:32:02Z","author_association":"NONE","body":"@clintongormley @spinscale \nI have seen a few similar issues like #4987 which had the same effect but was caused by a different error. Is there any reason why there are checks for specific errors in the bulk items and the errors that do not match those cause the full request to fail?\n\nRight now I index my documents in elasticsearch one by one but I am planing on queuing up our incoming data in redis and then bulk it in to optimize performance. The errors that could occur when those bulks are indexed cannot be known but I was hoping that if one index fails the others will not. Can I trust this to be the case?\n","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/51063359","html_url":"https://github.com/elastic/elasticsearch/issues/6410#issuecomment-51063359","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/6410","id":51063359,"node_id":"MDEyOklzc3VlQ29tbWVudDUxMDYzMzU5","user":{"login":"bytenik","id":441347,"node_id":"MDQ6VXNlcjQ0MTM0Nw==","avatar_url":"https://avatars0.githubusercontent.com/u/441347?v=4","gravatar_id":"","url":"https://api.github.com/users/bytenik","html_url":"https://github.com/bytenik","followers_url":"https://api.github.com/users/bytenik/followers","following_url":"https://api.github.com/users/bytenik/following{/other_user}","gists_url":"https://api.github.com/users/bytenik/gists{/gist_id}","starred_url":"https://api.github.com/users/bytenik/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/bytenik/subscriptions","organizations_url":"https://api.github.com/users/bytenik/orgs","repos_url":"https://api.github.com/users/bytenik/repos","events_url":"https://api.github.com/users/bytenik/events{/privacy}","received_events_url":"https://api.github.com/users/bytenik/received_events","type":"User","site_admin":false},"created_at":"2014-08-04T14:01:20Z","updated_at":"2014-08-04T14:01:20Z","author_association":"NONE","body":"Has any progress been made on this? Its a huge performance show-stopper for my company.\n","performed_via_github_app":null}]